# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ead954cd135523cefb5b41457675dc831ca05e786eadd5e49201f0a5ea43d3ad9a0413b5fd2e4f1203d7db3f62231d3940b441da352e0de538b40a4eec65385c

test:
  secret_key_base: 559904a15f1cde0c3f249251739774fc9c6c563261c78f718e27dd27922986f3d1ff91dd6c8b17eefe103f21a6afedcac1db659cc6b25ecc92bc6698a0944935

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
